# Site setings
name: 'Sean McCarthy'
description: "Data Scientist"
meta_description: "Sean McCarthy's thoughts and advice on software development, data science, economics, public policy, and finance."
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Hi there. My name is Sean McCarthy and I'm Chief Data Scientist at IJACK Technologies Inc. Welcome to my blog on software development and data science."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://mccarthysean.dev/
disqus: 'mccarthysean'
# mailchimp_url: 'https://myijack.us2.list-manage.com/subscribe/post?u=b4916eae2ad7cb10f5e629692&amp;id=3d9f3efd20'
mailchimp_url: 'https://dev.us2.list-manage.com/subscribe/post?u=b4916eae2ad7cb10f5e629692&amp;id=3d9f3efd20'
# Add your GA Tracking Id
ga_analytics: 'G-Z6DZ02583Q'

# Contact form setings
# "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
email: sean.mccarthy@live.ca
contact_page_description: 
thankyou_page_description: "Your message has been sent successfully. We will contact you very soon!"

# Social links
linkedin: 'seanmccarthy2'
medium: '@mccarthysean'
twitter: 'mccarthysean'
github: 'mccarthysean'
facebook: 'sean.mccarth'
instagram: 'mccarthysean'
# codepen: 'mccarthysean'
# dribbble: 'mccarthysean'
# pinterest: 'mccarthysean'
# producthunt: '@mccarthysean'
# quora: 'Sean-McCarthy-64'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  # - text: Style Guide
  #   url: /style-guide
  - text: Contact
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
